-- Adding transparency to nvim
-- require("everforest").setup({
--   disable_background = true,
-- })
--
-- function ColorMyPencils(color)
--   color = color or "everforest"
--   vim.cmd.colorscheme(color)

-- vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
-- end
--
-- ColorMyPencils()
